### ISSUE TITLE
Does dlmalloc need a separate repository?

### ISSUE THREAD

**Issue by bogdanm** [ARMmbed/dlmalloc#1]
Can't it be in mbed-alloc? If not, why?

**Comment by hugovincent** [comment]
One reason is so you can see what the upstream version is easily (e.g. in `yt ls`), but that would require (currently) that the version for this module is set to 2.8.6. Another reason might be that the license is different.

**Comment by bogdanm** [comment]
I don't expect the upstream to change too much, but even if it would, it wouldn't add too much noise in the already small `mbed-alloc` repo. It's perfectly OK to have repos with multiple licenses, that's already happening.

**Comment by bremoran** [comment]
A better point is "it adds another repo" isn't a good reason to NOT split things along logical boundaries.

**Comment by bogdanm** [comment]
I believe it is. Too much granularity with our repos is as bad as having everything in a single monolithic repo; think about all the maintenance nightmare created by the dependencies. Also, this isn't a logical boundary, this is still allocator code, and we have a repo for that :)

**Comment by rainierwolfcastle** [comment]
http://jira-dev0.cambridge.arm.com/browse/IOTSFW-874

**Comment by rainierwolfcastle** [comment]
ARM Internal Ref: IOTSFW-1000

**Comment by bremoran** [comment]
I don't think we should fix this since it works fine for now.  dlmalloc is also reusable on its own, so it makes sense to package it on its own.
